CREATE TABLE MEMBER(
	MEMBER_SEQ NUMBER NOT NULL,
	MEMBER_ID VARCHAR2(500) NOT NULL,
	MEMBER_PW VARCHAR2(500) NOT NULL,
	MEMBER_NAME VARCHAR2(500) NOT NULL,
	MEMBER_PHONE VARCHAR2(500) NOT NULL,
	MEMBER_EMAIL VARCHAR2(500) NOT NULL,
	MEMBER_ROLE NUMBER NOT NULL,
	MEMBER_DELFLAG CHAR(2) DEFAULT 'N' NOT NULL,
	MEMBER_OADDR VARCHAR2(500) NOT NULL,
	MEMBER_ADDR VARCHAR2(500) NOT NULL,
	MEMBER_DETAILADDR VARCHAR2(500) NOT NULL,
	MEMBER_DATE DATE DEFAULT SYSDATE,
	
	CONSTRAINT MEMBER_PK PRIMARY KEY(MEMBER_SEQ),
	CONSTRAINT MEMBER_UQ UNIQUE(MEMBER_EMAIL, MEMBER_PHONE)
);

DROP TABLE MEMBER
DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ;

SELECT * FROM MEMBER;

INSERT INTO MEMBER(MEMBER_SEQ, MEMBER_ID, MEMBER_PW, MEMBER_NAME, MEMBER_PHONE, MEMBER_EMAIL, MEMBER_ROLE, MEMBER_DELFLAG, MEMBER_ADDR, MEMBER_DATE)
VALUES(MEMBER_SEQ.NEXTVAL, 'admin', 'admin', '관리자', '01056068300', 'fkdkdk3@daum.net', 0, 'N', '관리자집', SYSDATE);